# numpy.org
#### Principal biblioteca de programaçao cientifica
#### Arrays numpy sao 50x mais rapidos de processar do que uma lista
#### Porem enquanto listas aceitam varios tipos de dados ,um array
#### numpy precisas ser de um unico tipo

In [1]:
#array python - é uma lista
arr=[0,1,2,3,4,5,6,7,8,9] #uma dimensao
type(arr)

list

In [3]:
#mais facil
arr= list(range(10))
print(arr)
type(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [4]:
#importa numpy com todas as funçoes
#import numpy #ou
import numpy as np
print('PI',np.pi)
#array numpy arange
arr= np.arange(10)
print(arr)
type(arr)

PI 3.141592653589793
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [5]:
#importa somente a funçao arange
from numpy import arange
print(arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#array numpy a partir de uma lista
arr=np.array([100,200,300,400])
print(arr)

[100 200 300 400]


In [7]:
#array a partir de uma tupla
arr=np.array((500,600,700,800))
print(arr)

[500 600 700 800]


In [9]:
#indexao
print(arr[0])
print(arr[1])
print(arr[2])

500
600
700


In [10]:
#               0   1   2   3   4   5   6
arr= np.array([100,200,300,400,500,600,700])
#seleçao
print(arr[0:3])
print(arr[2:])
print(arr[:3])
print(arr[2:4])
print(arr[-1])


[100 200 300]
[300 400 500 600 700]
[100 200 300]
[300 400]
700


In [11]:
#fatiamento
print(arr[0:5:2])
print(arr[0:6])

[100 300 500]
[100 200 300 400 500 600]


In [12]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [19]:
#constantes e metodos importantes do array numpy
arr= np.array([1,2,3,4,5])
print(arr)
print('Numero de dimensoes:',arr.ndim)
print('Tipo de objeto do python:',type(arr))
print('Tipo de dado numpy:',arr.dtype)
print('Tamanaho do array:',arr.size)
print('Formato do array:',arr.shape)

[1 2 3 4 5]
Numero de dimensoes: 1
Tipo de objeto do python: <class 'numpy.ndarray'>
Tipo de dado numpy: int32
Tamanaho do array: 5
Formato do array: (5,)


In [2]:
#funçoes do numpy
print('Minimo:',arr.min())
print('Maximo:',arr.max())
print('Media:',arr.mean())
print('Soma:',arr.sum())
print('Desvio padrao:',arr.std())

NameError: name 'arr' is not defined

# Criando arrays do zero

In [3]:
import numpy as np
a= np.zeros((3,2))
print(a)
a.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]]


(3, 2)

In [4]:
import numpy as np
a= np.zeros((2,3,2))
print(a)
a.shape

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


(2, 3, 2)

In [6]:
import numpy as np
a= np.ones((3))
print(a)
a.shape

[1. 1. 1.]


(3,)

# Criando ones do zero

In [7]:
import numpy as np
a= np.ones((3))
print(a)
a.shape

[1. 1. 1.]


(3,)

In [8]:
import numpy as np
a= np.ones((3,2))
print(a)
a.shape

[[1. 1.]
 [1. 1.]
 [1. 1.]]


(3, 2)

In [9]:
np.ones(a.shape)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.random.random((5,2))

array([[0.96551915, 0.45617749],
       [0.55269115, 0.28652001],
       [0.32507301, 0.33982117],
       [0.64675374, 0.6648508 ],
       [0.7161707 , 0.03043673]])

In [25]:
#gera 5 linhas entre 1 e 9
np.random.randint(1,10,5)

array([3, 5, 1, 5, 4])

In [28]:
np.random.randint(1,10,(2,3,2))


array([[[8, 9],
        [8, 4],
        [8, 8]],

       [[1, 4],
        [6, 2],
        [1, 4]]])

In [30]:
np.random.shuffle(a)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Propagação

In [32]:
a=np.array([-9,-3,7,-8,4])
b=np.array([10]) #1 elemento apenas
c=a+b
print(c)
d=a-b
print(d)

[ 1  7 17  2 14]
[-19 -13  -3 -18  -6]


In [33]:
a=np.array([15.0,20.0,22.0,75.0,40.0,35.0])
b=a/100
print(b)
d=a+1
print(d)

[0.15 0.2  0.22 0.75 0.4  0.35]
[16. 21. 23. 76. 41. 36.]


### operaçoes basicas sobre array

In [36]:
a=np.arange(9)
print(a)
b=a.reshape((3,3))
print(b)

#soma todos os numeros
print('Soma:',b.sum())

#Vetorização
#soma colunas
print('Soma colunas:',b.sum(axis=0))

#soma linhas
print('Soma linhas:',b.sum(axis=1))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Soma: 36
Soma colunas: [ 9 12 15]
Soma linhas: [ 3 12 21]


### multiplicaçao de matrizes

In [44]:
a=np.arange(1,2).reshape(2,3)
b=np.array([[1,0,0],
           [1,0,1,0],
           [1,0,0,1]
           ])
print(b)
print('\n',)
#multiplicando cada linha x cada coluna, somando
#np.dot(a,b)
a@b

ValueError: cannot reshape array of size 1 into shape (2,3)

In [45]:
#Vetoriza
dados=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.max(dados,axis=0) #coluna
np.max(dados,axis=1) #linha

array([3, 6, 9])

### Fatiamento

In [48]:
a=np.array([0,1,2,3,4,5])

In [50]:
print(a[0:5:2])

[0 2 4]


In [52]:
#fatiamento de atribuiçao
b=a[2:5]
print(b)
b[:]=9
print(b)

[9 9 9]
[9 9 9]


In [54]:
a=np.arange(20)
print(a)
a[5:10]=0
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19]


### map - Programaçao funcional

In [55]:
soma=0
lista=['1.1','3.3','5.0','7','9','11']
for x in lista:
    v=float(x) #converte string em float
    soma+=v
print(soma)

36.4


In [57]:
list(map(lambda x: float(x), lista))

[1.1, 3.3, 5.0, 7.0, 9.0, 11.0]

In [58]:
sum(map(lambda x: float(x), lista))

36.4