In [12]:
m2d =[[1,2,3],
    [4,5,6]
   ]
print('Matriz python 2D:',m2d)
print(m2d[0]) #linha 0
print(m2d[1]) #linha 1
print(m2d[0][0]) #linha 0, elemento 0 => 1
print(m2d[1][1])
print(m2d[:1])#so linha 0
print(len(m2d))#2 linhas
print(len(m2d[0]))#3 colunas
print(min(m2d))
print(max(m2d))

Matriz python 2D: [[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
[4, 5, 6]
1
5
[[1, 2, 3]]
2
3
[1, 2, 3]
[4, 5, 6]


In [13]:
m3d=[
        [
          [1,2,3],
          [4,5,6],
        ],
        [
          [255,255,255], 
          [255,0,0]
        ]
   ]
print('Matriz python:',m3d)
print(m3d[0])#nivel 0
print(m3d[0][0])#nivel 0,linha 0
print(m3d[0][0][0])#linha 0,linha 0,coluna 0
print(len(m3d)) #2 niveis
print(len(m3d[0]))#2 colunas
print(len(m3d[0][0]))#colunas
print('Tamanho:',len(m3d)*len(m3d[0])*len(m3d[0][0]))

Matriz python: [[[1, 2, 3], [4, 5, 6]], [[255, 255, 255], [255, 0, 0]]]
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
2
2
3
Tamanho: 12


#### Comparação array python x numpy

In [14]:
#Teste lista pyhton
import time
lista= list(range(1000000)) #1 milhão
ini=time.time()

for _ in range(100):
    lista=[x*2 for x in lista]
    
fim= time.time()    
dif1=fim - ini
print('Tempo array python:',dif1)


Tempo array python: 12.048290252685547


In [15]:
#Testa array com numpy
import numpy as np
arr=np.arange(1000000) #1 milhao
ini=time.time()

for _ in range(100):
    arr*=2
    
fim= time.time()    
dif2=fim-ini
print('Tempo array numpy:',dif2)

Tempo array numpy: 0.07100224494934082


In [16]:
print(dif1/dif2)

169.6888635180739


In [17]:
arr=np.arange(10)
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
lista=[1,2,3]
lista * 2

[1, 2, 3, 1, 2, 3]

#### Array numpy a partir de uma lista

In [19]:
#axis = 0 =>significa coluna
#axis = 1 =>significa linha

import numpy
lista = [
        [3,2,1],
        [6,5,4],
        [1,7,2]
        ]
matriz = numpy.array(lista)
print(type(matriz))
display(matriz)

<class 'numpy.ndarray'>


array([[3, 2, 1],
       [6, 5, 4],
       [1, 7, 2]])

In [20]:
#Propriedades do array no numpy
print('Numero de dimensões:',matriz.ndim) #2d
print('Tipod de objeto:',type(matriz))     #numpy.ndarray
print('Tipo de dado numpy:',matriz.dtype)  #data type= int 32 bits
print('Tamanho do array:',matriz.size)     #quantidade de itens
print('Formato do array:',matriz.shape)    #dimensoes:(2,3)
print('Linhas:',matriz.shape[0])
print('Colunas:',matriz.shape[1])

Numero de dimensões: 2
Tipod de objeto: <class 'numpy.ndarray'>
Tipo de dado numpy: int32
Tamanho do array: 9
Formato do array: (3, 3)
Linhas: 3
Colunas: 3


In [21]:
#Metodos ou funçoes dp array numpy
print('Minimo:',matriz.min())
print('Maximo:',matriz.max())
print('Media:',matriz.mean())
print('Soma:',matriz.sum())
print('Minimo:',matriz.min())
print('Desvio padrão:',matriz.std())

print('Minimo por coluna:',matriz.min(axis=0))
print('Minimo por linha:',matriz.min(axis=1))

print('Maximo por coluna:',matriz.max(axis=0))
print('Maximo por linha:',matriz.max(axis=1))

Minimo: 1
Maximo: 7
Media: 3.4444444444444446
Soma: 31
Minimo: 1
Desvio padrão: 2.060804110110156
Minimo por coluna: [1 2 1]
Minimo por linha: [1 4 1]
Maximo por coluna: [6 7 4]
Maximo por linha: [3 6 7]


In [23]:
#ordenaçao de matriz
matriz.sort()
display(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 7]])

In [24]:
#convete em lista
lista=matriz.tolist()
display(lista)

[[1, 2, 3], [4, 5, 6], [1, 2, 7]]

In [25]:
#seleçao
display(matriz[0]) #linha 0
display(matriz[1]) #linha 1
display(matriz[0].ndim) #1 dimensao
display(matriz[0].shape)#(3, )

array([1, 2, 3])

array([4, 5, 6])

1

(3,)

In [31]:
#referencinando linha, coluna
display(matriz[0][0]) #linha 0,coluna 0
#ou
display(matriz[0,0])

display(matriz[0,0].ndim) #0 dim = valor

v=matriz[0,0]
type(v) #numpy.int32

display(matriz[1,2]) #linha 1,coluna 2

1

1

0

6

In [46]:
import numpy as np
a = np.array([[3,2,1],[6,5,4]])
display(a)

array([[3, 2, 1],
       [6, 5, 4]])

In [47]:
#Fatiamento(seleçao com intervalos)
print(a[0][0:2]) #linha 0,coluna 0 e 1
#ou
print(a[0,0:2])

print(a[1][0:2]) #linha 1,coluna 0 e 1
#ou
print(a[1,0:2])

print('\n',a[0:1]) #devolve matriz com primeira linha
print('\n',a[0:2]) #matriz com primeira e segunda linhas
#fatimento
print('\n',a[0:2:2])

[3 2]
[3 2]
[6 5]
[6 5]

 [[3 2 1]]

 [[3 2 1]
 [6 5 4]]

 [[3 2 1]]


In [43]:
#Fatiamento(seleçao com intervalos)

print(a[0, 0:2])

TypeError: list indices must be integers or slices, not tuple