In [19]:
m=[[1,2,3],
  [4,5,6]]

In [20]:
print(m)

[[1, 2, 3], [4, 5, 6]]


In [21]:
display(m)

[[1, 2, 3], [4, 5, 6]]

In [22]:
print(m[0])

[1, 2, 3]


In [23]:
print(m[1])

[4, 5, 6]


In [24]:
#axis=0=> coluna
#axis=1=> linha

In [25]:
import numpy as np
matriz =np.array([(3, 2, 1), (6, 5, 4)])

In [26]:
display(matriz)

array([[3, 2, 1],
       [6, 5, 4]])

### propriedades da matriz numpy

In [27]:
print(matriz.ndim) #2 dimensoes
print(matriz.dtype) #int 32
print(matriz.shape) #(2,3)
print(matriz.shape[0]) #2 linhas
print(matriz.shape[1]) #3 colunas

2
int32
(2, 3)
2
3


In [31]:
print('Minimo:',matriz.min())
print('Maximo:',matriz.max())
print('Soma:',matriz.sum()) #soma todos os valores
print('Desvio Padrao:',matriz.std())
print('Desvio Padrao (colunas):',matriz.std(axis=0))
print('Desvio Padrao(linhas):',matriz.std(axis=1))
matriz.sort() #ordena
display(matriz)

Minimo: 1
Maximo: 6
Soma: 21
Desvio Padrao: 1.707825127659933
Desvio Padrao (colunas): [1.5 1.5 1.5]
Desvio Padrao(linhas): [0.81649658 0.81649658]


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
lista= matriz.tolist()
print(lista)

[[1, 2, 3], [4, 5, 6]]


In [33]:
import numpy as np
matriz =np.array([[3, 2, 1], 
                  [6, 5, 4]])
#seleçao
print(matriz[0]) #primeira linha
print(matriz[1]) #segunda linhas
print(matriz.ndim) #2D
print(matriz[0].ndim) #1D
print(type(matriz[0])) #cclass'numpy.ndarray

[3 2 1]
[6 5 4]
2
1
<class 'numpy.ndarray'>


In [35]:
print(matriz[0][0])#imprime 4
print(matriz[0,0])#imprime 4
print(matriz[0,0].ndim)#0 dim
print(matriz[1][2])
print(matriz[1,2])

3
3
0
4
4


#### Fatiamento(seleçao com intervalo)

In [36]:
display(matriz)

array([[3, 2, 1],
       [6, 5, 4]])

In [37]:
display(matriz[0][0:2])

array([3, 2])

#### Array de strings

In [39]:
import numpy as np
a=np.array(['kiwi','uva','banana'])
display(a)
print(a.dtype)

array(['kiwi', 'uva', 'banana'], dtype='<U6')

<U6


#### array a partir de arquivos inteiros
#### baixar softgraf.com/cursodatascience/carros-km.txt

#### lista =>array numpy =>Dataframe pandas

In [ ]:
lista